### ISSUE TITLE
Can you provide the processed dataset?

### ISSUE THREAD

**Issue by miyya0707** [dawn0815/UniSA#1]

**Comment by lizaijing** [comment]
Due to copyright restrictions on some of the datasets, we have decided to provide the dataset processing scripts first, and you can use the scripts we provide to format all the datasets, subject to obtaining a license for the original datasets. We will verify copyright claims and release licensed datasets soon.

**Comment by version98** [comment]
Looking forward to your processed dataset

**Comment by lizaijing** [comment]
If you are in urgency for the processed datasets, you can contact us at lzj14011@gmail.com
