### ISSUE TITLE
Missing File

### ISSUE THREAD

**Issue by CREN24** [dawn0815/UniSA#3]
Hi, Can I get .py file for generate concat_pretrain.pkl and concat_val.pkl? The file for concat_val.pkl is missing and process_concat.py is incomplete. Thanks

**Comment by lizaijing** [comment]
Since the pre-training data is obtained by combining multiple datasets, it is very voluminous. For example, Amazon Review has 0.2 billion of entries. We recommend obtaining a licence for the raw data on your own and pre-processing the data, then formatting it using the scripts we provide. If you are interested in the processed data, feel free to contact with me via lzj14011[AT]gmail.com
